import csv
import io
import json
import uuid
from datetime import datetime, timezone, timedelta

from database import get_db
from models.db_models import get_task, get_logs


def _now():
    return datetime.now(timezone.utc).isoformat()


def _id():
    return uuid.uuid4().hex


def _generate_share_token():
    return uuid.uuid4().hex[:16]


async def generate_html_report(task_id: str) -> str:
    async with get_db() as db:
        task = await get_task(db, task_id)
        logs = await get_logs(db, task_id)
    if not task:
        return "<html><body><h1>Task not found</h1></body></html>"

    log_rows = ""
    for log in logs[:100]:
        log_rows += f"<tr><td>{log.get('agent_name', '')}</td><td>{log.get('action_type', '')}</td><td>{log.get('tool_name', '') or '-'}</td><td>{(log.get('content', '') or '')[:200]}</td><td>{log.get('timestamp', '')[:19]}</td></tr>"

    result_html = (task.get("result") or "No result").replace("\n", "<br>")

    return f"""<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>AutoPilot Report: {task.get('goal', '')[:60]}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; color: #1a1a1a; }}
h1 {{ color: #10b981; font-size: 24px; }}
h2 {{ color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; }}
.meta {{ color: #6b7280; font-size: 14px; margin: 12px 0; }}
.status {{ display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 600; }}
.status-completed {{ background: #d1fae5; color: #065f46; }}
.status-failed {{ background: #fee2e2; color: #991b1b; }}
.result {{ background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 16px 0; line-height: 1.6; }}
table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
th, td {{ border: 1px solid #e5e7eb; padding: 8px; text-align: left; }}
th {{ background: #f3f4f6; font-weight: 600; }}
td {{ max-width: 300px; overflow: hidden; text-overflow: ellipsis; }}
.footer {{ margin-top: 40px; color: #9ca3af; font-size: 12px; text-align: center; }}
</style>
</head><body>
<h1>AutoPilot Task Report</h1>
<div class="meta">
<strong>Goal:</strong> {task.get('goal', '')}<br>
<strong>Status:</strong> <span class="status status-{task.get('status', 'pending')}">{task.get('status', 'pending')}</span><br>
<strong>Created:</strong> {(task.get('created_at') or '')[:19]}<br>
<strong>Completed:</strong> {(task.get('completed_at') or 'N/A')[:19]}<br>
<strong>Tokens:</strong> {task.get('total_tokens', 0):,} · <strong>Iterations:</strong> {task.get('total_iterations', 0)} · <strong>Tool Calls:</strong> {task.get('total_tool_calls', 0)}
</div>
<h2>Result</h2>
<div class="result">{result_html}</div>
<h2>Execution Log</h2>
<table>
<tr><th>Agent</th><th>Action</th><th>Tool</th><th>Content</th><th>Time</th></tr>
{log_rows}
</table>
<div class="footer">Generated by AutoPilot · {_now()[:19]}</div>
</body></html>"""


async def generate_csv_report(task_id: str) -> str:
    async with get_db() as db:
        task = await get_task(db, task_id)
        logs = await get_logs(db, task_id)
    if not task:
        return ""

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Agent", "Action", "Tool", "Content", "Tokens", "Duration (ms)", "Timestamp"])
    for log in logs:
        writer.writerow([
            log.get("agent_name", ""),
            log.get("action_type", ""),
            log.get("tool_name", "") or "",
            (log.get("content", "") or "")[:500],
            log.get("tokens_used", 0),
            log.get("duration_ms", 0),
            log.get("timestamp", ""),
        ])
    return output.getvalue()


async def create_shared_report(task_id: str, title: str, fmt: str, created_by: str = "", expires_hours: int = 168) -> dict:
    report_id = _id()
    share_token = _generate_share_token()

    if fmt == "html":
        content = await generate_html_report(task_id)
    elif fmt == "csv":
        content = await generate_csv_report(task_id)
    else:
        content = await generate_html_report(task_id)
        fmt = "html"

    expires_at = (datetime.now(timezone.utc) + timedelta(hours=expires_hours)).isoformat()

    async with get_db() as db:
        await db.execute(
            "INSERT INTO shared_reports (id, task_id, title, format, content, share_token, expires_at, view_count, created_by, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?, ?)",
            (report_id, task_id, title, fmt, content, share_token, expires_at, created_by, _now()),
        )
        await db.commit()

    return {"id": report_id, "share_token": share_token, "format": fmt, "expires_at": expires_at}


async def get_shared_report(share_token: str) -> dict | None:
    async with get_db() as db:
        cursor = await db.execute("SELECT * FROM shared_reports WHERE share_token = ?", (share_token,))
        row = await cursor.fetchone()
        if not row:
            return None
        report = dict(row)
        if report.get("expires_at") and report["expires_at"] < _now():
            return None
        await db.execute(
            "UPDATE shared_reports SET view_count = view_count + 1 WHERE share_token = ?",
            (share_token,),
        )
        await db.commit()
    return report


async def list_shared_reports(task_id: str | None = None) -> list[dict]:
    async with get_db() as db:
        if task_id:
            cursor = await db.execute(
                "SELECT id, task_id, title, format, share_token, expires_at, view_count, created_at FROM shared_reports WHERE task_id = ? ORDER BY created_at DESC",
                (task_id,),
            )
        else:
            cursor = await db.execute(
                "SELECT id, task_id, title, format, share_token, expires_at, view_count, created_at FROM shared_reports ORDER BY created_at DESC LIMIT 50"
            )
        rows = await cursor.fetchall()
    return [dict(r) for r in rows]


async def delete_shared_report(report_id: str):
    async with get_db() as db:
        await db.execute("DELETE FROM shared_reports WHERE id = ?", (report_id,))
        await db.commit()
